apiVersion: v1
kind: Secret
metadata:
  name: csi-proxmox-config
  namespace: kaas
type: addons.cluster.x-k8s.io/resource-set
stringData:
  config.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: proxmox-csi-plugin
      namespace: csi-proxmox
    stringData:
      config.yaml: |
        clusters:
          - url: https://192.168.10.138:8006/api2/json
            insecure: true
            token_id: "kubernetes-csi@pve!kaas"
            token_secret: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            # ProxmoxのClusterを指定する
            region: region1
