apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-class-proxmox
  namespace: kaas
data:
  storage-class.yaml: |
    # 指摘できるパラメーター一覧
    # https://github.com/sergelogvinov/proxmox-csi-plugin/blob/main/docs/options.md
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: proxmox-data
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    provisioner: csi.proxmox.sinextra.dev
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
    reclaimPolicy: Delete
    parameters:
      csi.storage.k8s.io/fstype: ext4
      storage: local-lvm
